#155738437 Setup Repo
NabunyaLilian/ConvergeCodeLab pull request #2
Opened 2019-03-22 13:59 UTC by NabunyaLilian

**What does this PR do**
- Sets up the project repository
**Tasks to be completed**
- Set up IDE (Android Studio)
- Initialise android app folder with git
- Customise color palette

**Relevant PT stories**
[155738437](https://www.pivotaltracker.com/story/show/155738437)
[#155738456](https://www.pivotaltracker.com/story/show/155738456)

2019-03-24 12:21 UTC, johngorithm requested changes
Good Job @NabunyaLilian 
Kindly attend the reviews below and equally ensure to `gitignore` the contents of `.idea/` directory.

Learn about what to ignore in an Android project.
[Useful Link](https://proandroiddev.com/deep-dive-into-idea-folder-in-android-studio-53f867cf7b70)

2019-03-24 12:21 UTC, johngorithm commented on tools/script-findbugs.gradle
> +apply plugin: 'findbugs'
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on tools/rules-pmd.xml
> +<?xml version="1.0"?>
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on tools/rules-findbugs.xml
> +<FindBugsFilter>
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on tools/rules-checkstyle.xml
> +<?xml version="1.0"?>
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on tools/pmd.gradle
> +apply plugin: 'pmd'
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on tools/checkstyle.gradle
> +
This file is not expected in this PR. Kindly remove it

2019-03-24 12:21 UTC, johngorithm commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">My Application</string>
Change this to reflect your application's name. Be creative with that 👍

2019-03-24 12:21 UTC, johngorithm commented on app/src/main/java/com/example/thecodelab/MainActivity.java
> +    private void someMethod(int variable) {
Remove this redundant method

2019-03-24 12:21 UTC, johngorithm commented on .circleci/config.yml
> +version: 2
This file is not expected in this PR. Kindly remove it

2019-03-25 06:22 UTC, NabunyaLilian commented
thanks for the feedback @johngorithm, I have worked on it.

2019-03-25 09:30 UTC, johngorithm commented on .gitignore
> +tools/
👁 👁

2019-03-25 09:35 UTC, johngorithm approved these changes
LGTM

2019-03-28 07:25 UTC, joshNic approved these changes
LGTM am merging this

2019-03-28 07:25 UTC, merged